MVCDemoApp/MVCDemoApp/Models/Attendee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MVCDemoApp.Models
{
    public class Attendee
    {
        [Required(ErrorMessage = "Name is compulsory field")]
        [StringLength(10, ErrorMessage = "Maximum Name length is 10 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email is compulsory field")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone is compulsory field")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$")]
        public int? Phone { get; set; }

        [Required(ErrorMessage = "Select any one option")]
        public string WillAttend { get; set; }
    }
}

MVCDemoApp/MVCDemoApp/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MVCDemoApp.Models
{
    public class Employee
    {
        [Required(ErrorMessage = "EmpId is compulsory field")]
        [RegularExpression(@"[0-9]{4}", ErrorMessage = "Enter four digit EmpID")]
        public int EmpId { get; set; }

        [Required(ErrorMessage = "EmpName is compulsory field")]
        [StringLength(10, ErrorMessage = "Maximum EmpName length is 10 characters")]
        public string EmpName { get; set; }

        [Required(ErrorMessage = "Salary is compulsory field")]
        public double? Salary { get; set; }
    }
}

MVCDemoApp/MVCDemoApp/Models/ErrorViewModel.cs
using System;

namespace MVCDemoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCDemoApp/MVCDemoApp/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCDemoApp.Models;

namespace MVCDemoApp.Controllers
{
    public class AssignmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AttendeeForm()
        {
            return View(new Attendee());
        }

        public IActionResult DisplayAttendeeData(Attendee attendee)
        {
            ViewBag.DefaultMessage = "Thank You " + attendee.Name;
            if (attendee.WillAttend == "Yes")
            {
                ViewBag.Message = "It's great that you're coming";
            }
            if (attendee.WillAttend == "No")
            {
                ViewBag.Message = "Sorry to hear that you can't make it, but thanks for letting us know";
            }

            return View();

        }
    }
}

MVCDemoApp/MVCDemoApp/Controllers/DataPersistantDemoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using MVCDemoApp.Models;
using Microsoft.Extensions.Configuration;

namespace MVCDemoApp.Controllers
{
    public class DataPersistantDemoController : Controller
    {
        public IConfiguration Configuration { get; }

        public DataPersistantDemoController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IActionResult Index()
        {
            ViewBag.data = Configuration["CustomKey"];
            return View();
        }

        public IActionResult SessionDemo()
        {
            //create session values
            //HttpContext.Session.SetString(key, value)
            HttpContext.Session.SetString("message", "Session test");
            HttpContext.Session.SetInt32("count", 5);

            HttpContext.Session.SetString("dateobj", JsonSerializer.Serialize(DateTime.Now));

            Employee employee = new Employee() { EmpId = 101, EmpName = "Alisha", Salary = 300000 };
            string empserializedata = JsonSerializer.Serialize(employee);
            HttpContext.Session.SetString("empobj", empserializedata);

            return RedirectToAction("GetSessionValues");
        }

        public IActionResult GetSessionValues()
        {
            //read session values
            ViewBag.message = HttpContext.Session.GetString("message"); 
            ViewBag.count = HttpContext.Session.GetInt32("count");

            var dateobj = HttpContext.Session.GetString("dateobj");
            ViewBag.date = JsonSerializer.Deserialize<DateTime>(dateobj);

            string emp = HttpContext.Session.GetString("empobj");
            Employee empobj = JsonSerializer.Deserialize<Employee>(emp);
            ViewBag.emp = empobj;

            return View();
        }

        public IActionResult WriteCookies(string setting, string settingValue, bool isPersistent)
        {
            if (isPersistent)
            {
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Append(setting, settingValue, options);
            }
            else //session cookie
            {
                Response.Cookies.Append(setting, settingValue);
            }
            ViewBag.Message = "Cookie Written Successfully!";
            return View("Index");
        }

        public IActionResult ReadCookies()
        {
            ViewBag.FontName = Request.Cookies["fontName"];
            ViewBag.FontSize = Request.Cookies["fontSize"];
            ViewBag.Color = Request.Cookies["color"];

            if(string.IsNullOrEmpty(ViewBag.FontName))
            {
                ViewBag.FontName = "Arial";
            }
            if (string.IsNullOrEmpty(ViewBag.FontSize))
            {
                ViewBag.FontSize = "22px";
            }
            if (string.IsNullOrEmpty(ViewBag.FontName))
            {
                ViewBag.Color = "Black";
            }
            return View();
        }

    }
}





MVCDemoApp/MVCDemoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCDemoApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDemoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [Route("Home/Greet/{name}")]
        public IActionResult Greet(string name)
        {
            //return Content("Welcome to MVC");
            //return View("Greet1");
            ViewBag.wish = "Hello " + name;
            return View();
        }

        //Create an action - AddNumbers
        //which takes two integer parameters
        //display addition of numbers in browser

        [Route("Home/AddNumbers/{n1?}/{n2?}")]
        public IActionResult AddNumbers(int n1, int n2)
        {
            int result = n1 + n2;
            ViewBag.result = $" {n1} + {n2} = {result}";
            //ViewBag.result = n1 + n2;
            return View();
        }

        [HttpPost("home/sum/{num1:int}/{num2:int:range(1,10)}")]
        public IActionResult AddNum(int num1=0, int num2=0)
        {
            int result = num1 + num2;
            ViewBag.result = result;
            return View();
        }

        public IActionResult GetData(int id)
        {
            ViewBag.message = "Id = " + id;
            return View();
        }

        public IActionResult ModelDemo()
        {
            Employee employee = new Employee { EmpId = 1, EmpName = "alisha", Salary = 10000 };
            //ViewBag.emp = employee;
            ViewData["emp"] = employee;
            return View();
        }

        public IActionResult EmployeeForm()
        { 
            return View(new Employee());
        }

        public IActionResult DisplayEmployeeData(Employee employee)
        { 
            if(ModelState.IsValid)
            {
                return View(employee);
            }
            return View("EmployeeForm", employee);
            
        }

        


    }
}

MVCDemoApp/MVCDemoApp/Views/Assignment/AttendeeForm.cshtml
@model Attendee
@{
    ViewData["Title"] = "AttendeeForm";
}

<h1>RegistrationForm</h1>

<form asp-controller="Assignment" asp-action="DisplayAttendeeData" method="post">
    <div asp-validation-summary="All" class="text text-danger"></div>

    Name : <input type="text" asp-for="Name" class="form-control" />
    <span asp-validation-for="Name"></span>
    <br />

    Email : <input type="email" asp-for="Email " class="form-control" />
    <span asp-validation-for="Email"></span>
    <br />

    Phone :<input type="tel" asp-for="Phone" class="form-control" />
    <span asp-validation-for="Phone"></span>
    <br />

    <div>
        WillAttend
        <span asp-validation-for="WillAttend"></span>

        <span asp-validation-for="WillAttend"></span>
        <select asp-for="WillAttend" class="form-control" aria-labelledby="btnDropdownDemo">
            <option selected disabled>---Confirmation---</option>
            <option class="dropdown-item" value="Yes">Yes</option>
            <option class="dropdown-item" value="No">No</option>
        </select>
    </div>
    <br />
    <button type="submit" class="btn btn-outline-success">Submit</button>
</form>

MVCDemoApp/MVCDemoApp/Views/Assignment/DisplayAttendeeData.cshtml
@model Attendee 
@{
    ViewData["Title"] = "DisplayAttendeeData";
}

<h1>DisplayAttendeeData</h1>

<h1>@ViewBag.DefaultMessage</h1>

<h4>@ViewBag.Message</h4>

MVCDemoApp/MVCDemoApp/Views/Assignment/Index.cshtml

@{
    ViewData["Title"] = "Index";
}

<h1>Welcome to the Event!!!</h1>
<br />

<img src="/images/event.jpg" width="400" height="400" />

<br />
<a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="AttendeeForm">Register</a>


MVCDemoApp/MVCDemoApp/Views/Assignment/RegistrationForm.cshtml
@model Attendee
@{
    ViewData["Title"] = "AttendeeForm";
}

<h1>RegistrationForm</h1>

<form asp-controller="Assignment" asp-action="DisplayAAttendeeData" method="post">
    <div asp-validation-summary="All" class="text text-danger"></div>

    Name : <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name"></span>
    <br />

    Email : <input asp-for="Email " class="form-control" />
    <span asp-validation-for="Email"></span>
    <br />

    Phone :<input asp-for="Phone" class="form-control" />
    <span asp-validation-for="Phone"></span>
    <br />

    <div>
        WillAttend
        <span asp-validation-for="WillAttend"></span>

        <span asp-validation-for="WillAttend"></span>
        <select asp-for="WillAttend" class="form-control" aria-labelledby="btnDropdownDemo">
            <option selected disabled>---Confirmation---</option>
            <option class="dropdown-item" value="Yes">Yes</option>
            <option class="dropdown-item" value="No">No</option>
        </select>
    </div>
    <br />
    <button type="submit" class="btn btn-outline-success">Submit</button>
</form>

MVCDemoApp/MVCDemoApp/Views/DataPersistantDemo/GetSessionValues.cshtml

@{
    ViewData["Title"] = "GetSessionValues";
}

<h1>GetSessionValues</h1>



@ViewBag.message
<br />
@ViewBag.Count
<br />
@ViewBag.date
<br />

<hr />
@ViewBag.emp.EmpId
<br />
@ViewBag.emp.EmpName
<br />
@ViewBag.emp.Salary

MVCDemoApp/MVCDemoApp/Views/DataPersistantDemo/Index.cshtml

@{
    ViewData["Title"] = "Index";
}

@ViewBag.data
<br />

<h1>Specify your preferences :</h1>
<form asp-action="WriteCookies" asp-controller="DataPersistantDemo">
    <select name="setting">
        <option value="fontName">Font Name</option>
        <option value="fontSize">Font Size</option>
        <option value="color">Color</option>
    </select>

    <input type="text" name="settingValue" />
    <input type="checkbox" name="isPersistent" value="true" />Is Persistent?
    <input type="submit" value="Write Cookie" />
</form>

<h4>@ViewBag.Message</h4>
<h4>
    <a asp-action="ReadCookies" asp-controller="DataPersistantDemo">
        Read Cookies
    </a>
</h4>

MVCDemoApp/MVCDemoApp/Views/DataPersistantDemo/ReadCookies.cshtml

@{
    ViewData["Title"] = "ReadCookies";
}

<h1>ReadCookies</h1>

<div style="font-family:'@ViewBag.FontName';
            font-size:@ViewBag.FontSize;
            color: @ViewBag.Color">
    Hello World!
</div>
    


MVCDemoApp/MVCDemoApp/Views/Home/AddNum.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNum</title>
</head>
<body>
    <h3>
        @ViewBag.result
    </h3>
</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Home/AddNumbers.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNumbers</title>
</head>
<body>
    <h3>@ViewBag.result</h3>
</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Home/DisplayEmployeeData.cshtml
@model Employee
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DisplayEmployeeData</title>
</head>
<body>
    <h3>Employee Data</h3>

    @Model.EmpId <br />
    @Model.EmpName <br />
    @Model.Salary <br />

</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Home/EmployeeForm.cshtml
@model Employee
@{
    ViewData["Title"] = "EmployeeForm";
}

<h1>EmployeeForm</h1>

<form asp-controller="Home" asp-action="DisplayEmployeeData" method="post">
    <div asp-validation-summary="All" class="text text-danger"></div>

    EmpId : <input type="text" asp-for="EmpId" class="form-control" />
    <span asp-validation-for="EmpId"></span>
    <br />

    EmpName : <input asp-for="EmpName" class="form-control" />
    <span asp-validation-for="EmpName"></span>
    <br />

    Salary : <input asp-for="Salary " class="form-control" />
    <span asp-validation-for="Salary"></span>
    <br />
    <button type="submit" class="btn btn-outline-success">Submit</button>
</form>

MVCDemoApp/MVCDemoApp/Views/Home/GetData.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetData</title>
</head>
<body>
    <h3>
        @ViewBag.message
    </h3>
</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Home/Greet.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Greet</title>
</head>
<body>
    <h2>Welcome to MVC View</h2>
    <h3>@ViewBag.wish</h3>
</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>



MVCDemoApp/MVCDemoApp/Views/Home/ModelDemo.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ModelDemo</title>
</head>
<body>
    <h3>Employee Data</h3>
    @*@ViewBag.emp.EmpId <br />
        @ViewBag.emp.EmpName <br />
        @ViewBag.emp.Salary <br />*@

    @{
        Employee emp = ViewData["emp"] as Employee;
    }
    @emp.EmpId <br />
    @emp.EmpName <br />
    @emp.Salary <br />

</body>
</html>

MVCDemoApp/MVCDemoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="EmployeeForm">EmployeeForm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataPersistantDemo" asp-action="Index">DataPersistantDemo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataPersistantDemo" asp-action="SessionDemo">SessionDemo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="">EventPage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCDemoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>